>Sequence1|fragment1
CGTAATTTTCCCGGCGTCA
>Sequence1|fragment2
ACGCGTTTCCCCT
>Sequence1|fragment3
CCCCTTTATTGTGGTTG
>Sequence2|fragment1
GGGATGAGCCCGGCA
>Sequence2|fragment2
CAACGCGTGCCACGCCC
>Sequence3|fragment1
GTATGTCTGGAA
>Sequence3|fragment2
AACCCGTCCCC
>Sequence3|fragment3
TACCATTATCGGTG
>Sequence4|fragment1
CTATCTCCCATGTCGCT
>Sequence4|fragment2
TCAGCCCACGTGTT
>Sequence5|fragment1
TTTTTCCCCACGCAA
>Sequence5|fragment2
GGTTCCCTCC
>Sequence5|fragment3
CCTATTGTGGGT